resolver: lts-9.13

packages:
- .
- location:
    git: git@github.com:hexresearch/config-app.git
    commit: a23131b
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- concurrent-extra-0.7.0.11

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
